name: Build

on: [push]

jobs:
  appimage:
    name: AppImage
    runs-on: ubuntu-18.04
    steps:
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:gnuradio/gnuradio-releases
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends cmake qt5-default qt5-gtk-platformtheme qttranslations5-l10n libqt5svg5-dev libboost-dev libpulse-dev portaudio19-dev liblog4cpp5-dev gnuradio-dev libairspy-dev libairspyhf-dev libfreesrp-dev libhackrf-dev librtlsdr-dev libsoapysdr-dev soapysdr-module-remote libuhd-dev liborc-0.4-dev libhidapi-dev

          cd /tmp
          git clone https://github.com/Nuand/bladeRF.git
          cd bladeRF
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr ..
          make -j4
          sudo make install
          sudo ldconfig

          cd /tmp
          git clone https://github.com/dl1ksv/gr-fcdproplus.git
          cd gr-fcdproplus
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr ..
          make -j4
          sudo make install
          sudo ldconfig

          cd /tmp
          git clone https://gitea.osmocom.org/sdr/libosmo-dsp.git
          cd libosmo-dsp
          autoreconf -i
          ./configure --prefix=/usr
          make -j4
          sudo make install
          sudo ldconfig

          cd /tmp
          git clone https://gitea.osmocom.org/sdr/gr-iqbal.git
          cd gr-iqbal
          git checkout gr3.8
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_MODULES_DIR=/usr/lib/x86_64-linux-gnu/cmake ..
          make -j4
          sudo make install
          sudo ldconfig

          cd /tmp
          git clone https://gitea.osmocom.org/sdr/gr-osmosdr.git
          cd gr-osmosdr
          git checkout gr3.8
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_MODULES_DIR=/usr/lib/x86_64-linux-gnu/cmake ..
          make -j4
          sudo make install
          sudo ldconfig
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure
        run: mkdir build && cd build && cmake ..
      - name: Compile
        working-directory: build
        run: make -j4
      - name: Build AppImage
        run: ./appimage.sh
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: gqrx-appimage-${{ github.run_id }}
          path: Gqrx-*.AppImage
  appimagearm-arm:
    name: AppImage ARM
    runs-on: [self-hosted, linux, ARM]
    steps:
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:gnuradio/gnuradio-releases
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends cmake qt5-default qt5-gtk-platformtheme qttranslations5-l10n libqt5svg5-dev libboost-dev libpulse-dev portaudio19-dev liblog4cpp5-dev gnuradio-dev libairspy-dev libairspyhf-dev libfreesrp-dev libhackrf-dev librtlsdr-dev libsoapysdr-dev soapysdr-module-remote libuhd-dev liborc-0.4-dev libhidapi-dev

          cd /tmp
          git clone https://github.com/Nuand/bladeRF.git
          cd bladeRF
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr ..
          make -j4
          sudo make install
          sudo ldconfig

          cd /tmp
          git clone https://github.com/dl1ksv/gr-fcdproplus.git
          cd gr-fcdproplus
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr ..
          make -j4
          sudo make install
          sudo ldconfig

          cd /tmp
          git clone https://gitea.osmocom.org/sdr/libosmo-dsp.git
          cd libosmo-dsp
          autoreconf -i
          ./configure --prefix=/usr
          make -j4
          sudo make install
          sudo ldconfig

          cd /tmp
          git clone https://gitea.osmocom.org/sdr/gr-iqbal.git
          cd gr-iqbal
          git checkout gr3.8
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_MODULES_DIR=/usr/lib/x86_64-linux-gnu/cmake ..
          make -j4
          sudo make install
          sudo ldconfig

          cd /tmp
          git clone https://gitea.osmocom.org/sdr/gr-osmosdr.git
          cd gr-osmosdr
          git checkout gr3.8
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_MODULES_DIR=/usr/lib/x86_64-linux-gnu/cmake ..
          make -j4
          sudo make install
          sudo ldconfig
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure
        run: mkdir build && cd build && cmake ..
      - name: Compile
        working-directory: build
        run: make -j4
      - name: Build AppImage
        run: ./appimage.sh
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: gqrx-appimage-arm-${{ github.run_id }}
          path: Gqrx-*.AppImage
